# Generated by Django 3.2.25 on 2026-06-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_answerlog_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='media_url',
            field=models.URLField(blank=True, default='', help_text='Mega / YouTube / Vimeo / direct media link. If set, it plays from here instead of an upload.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='archive',
            name='is_Audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archive',
            name='is_Image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archive',
            name='is_Video',
            field=models.BooleanField(default=False),
        ),
    ]
